### ISSUE TITLE
Add one more signature to exist Transaction.

### ISSUE THREAD

**Issue by TheHmmka** [p2p-org/solana-swift#18]
Hello everyone!
I get Transaction with signature from the backend and I need to add my own signature and sign transaction. So I will have two signature (first for paying fee, second is mine). But when I add my own signature I get error from Solana endpoint:
```
failed to send transaction: Transaction signature verification failure
```

I have created method for this (example from NodeJS) without overriding `signature` array:
```
public mutating func partialSign(signers: [Account]) throws {
            guard signers.count > 0 else { throw Error.invalidRequest(reason: "No signers") }
            
            // unique signers
            let signers = signers.reduce([Account](), { signers, signer in
                var uniqueSigners = signers
                if !uniqueSigners.contains(where: { $0.publicKey == signer.publicKey }) {
                    uniqueSigners.append(signer)
                }
                return uniqueSigners
            })
            
            // construct message
            let message = try compile()
            try partialSign(message: message, signers: signers)
        }
```
Does anybody can help me to add one more sign without error from Solana?

**Comment by bigearsenal** [comment]
Hi there, please upgrade to solana-swift 2.0.0 which supports swift concurrency & multiple signers
