### ISSUE TITLE
getSignaturesForAddress and getTransaction hardcoded for mainnet

### ISSUE THREAD

**Issue by acorscadden** [p2p-org/solana-swift#2]
I noticed that `getSignaturesForAddress` and `getTransaction` are both hardcoded to mainnet via an `overridingEndpoint` param. Is there a reason that we can't use testnet or devnet with these functions? In my build, I've just commented out the `overridingEndpoint` and it seems to work fine. 

On a side note, I just started playing around with `solana-swift` and this is a great library so far....nice work!

**Comment by bigearsenal** [comment]
Thanks. I'm fixing it

**Comment by bigearsenal** [comment]
Hi there, we released 2.0.0, please update it
