### ISSUE TITLE
'Task' is only available in iOS 15.0 or newer

### ISSUE THREAD

**Issue by IhorStasiv** [p2p-org/solana-swift#52]
When i do pod instal with your lib, my project say <'Task' is only available in iOS 15.0 or newer> 
but i already change deployment target to IOS 15, and it still <'Task' is only available in iOS 15.0 or newer>

**Comment by bigearsenal** [comment]
Hi there, which version of xcode/swift are you using?

**Comment by bigearsenal** [comment]
It works in after iOS 13.0 with Xcode 13.2.1 !

**Comment by IhorStasiv** [comment]
> It works in after iOS 13.0 with Xcode 13.2.1 !

Thanks I will update my version of xcode

**Comment by IhorStasiv** [comment]
it work after update Xcode ty
