### ISSUE TITLE
Can't send SPL transaction

### ISSUE THREAD

**Issue by IhorStasiv** [p2p-org/solana-swift#53]
So thats is my code 

       private func transferSolanaToken(mnemonic: [String], wallet: HDWallet) {
        try async {
            let endpoint = APIEndPoint(
                address: "https://api.mainnet-beta.solana.com",
                network: .mainnetBeta
            )
            do {
                let account = try await Account(phrase: mnemonic, network: .mainnetBeta, derivablePath: .default)
                let blockchainClient = BlockchainClient(apiClient: JSONRPCAPIClient(endpoint: endpoint))
                let preparedTransaction = try await blockchainClient.prepareSendingSPLTokens(
                    account: account,
                    mintAddress: "cxxShYRVcepDudXhe7U62QHvw8uBJoKFifmzggGKVC2",  // USDC mint
                    decimals: 6,
                    from: "DnTwkxa6xtFB72w2t9PPrwuxksAR1Gb663UWTGLbVpYM", // Your usdc address
                    to: "W3LJP23kwe4Vt6E2cpZ5DRHSNiJxfYwTxg8zuTmTKAT",
                    amount: UInt64(1)
                )
                
                print(preparedTransaction)
                
                let result = try await blockchainClient.sendTransaction(preparedTransaction: 
          preparedTransaction.preparedTransaction)
                
                print(result)
            }
            catch {
                print("error")
            }
        }
     }
    
its fail at result line
where is my fail? 
can i look some example of this transactions anywhere?
i try do like readme but it didn't work :c

**Comment by bigearsenal** [comment]
Hi there! The amount is too small, 1 mean 0.000001, it may cause problem. Please try with another amount,

**Comment by IhorStasiv** [comment]
> Hi there! The amount is too small, 1 mean 0.000001 usdc (1*10^-6). Small amount may cause problem. Please try with another amount. Plus, it would be better if you print concrete error. If not, I can not help you further with your problem

I try do this transaction with 1 but with decimal 0 and it still fail.
and i cant print error cose this code not throw any one, just go to catch block that all.
the last printed value from do block its "preparedTransaction"
   (preparedTransaction: SolanaSwift.PreparedTransaction(transaction: 
   SolanaSwift.Transaction(signatures: [SolanaSwift.Transaction.Signature(signature: 
   Optional(64 bytes), publicKey: 
   27YLmwU5vJSFyNFfGZLhcfe3j6YZ8sEAgcbgFVviVfsW)], feePayer: 
   Optional(27YLmwU5vJSFyNFfGZLhcfe3j6YZ8sEAgcbgFVviVfsW), instructions: 
   [SolanaSwift.TransactionInstruction(keys: [{"publicKey": 
   "27YLmwU5vJSFyNFfGZLhcfe3j6YZ8sEAgcbgFVviVfsW", "isSigner": true, "isWritable": 
   true}, {"publicKey": "9NUu2yxzfarkDRsC82hhqdU6Bg6DnHiysteLvbQtkSMq", 
   "isSigner": false, "isWritable": true}, {"publicKey": 
   "W3LJP23kwe4Vt6E2cpZ5DRHSNiJxfYwTxg8zuTmTKAT", "isSigner": false, 
   "isWritable": false}, {"publicKey": 
   "cxxShYRVcepDudXhe7U62QHvw8uBJoKFifmzggGKVC2", "isSigner": false, 
   "isWritable": false}, {"publicKey": "11111111111111111111111111111111", "isSigner": false, 
   "isWritable": false}, {"publicKey": 
   "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", "isSigner": false, 
   "isWritable": false}, {"publicKey": "SysvarRent111111111111111111111111111111111", 
   "isSigner": false, "isWritable": false}], programId: 
   ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL, data: []), 
   SolanaSwift.TransactionInstruction(keys: [{"publicKey": 
   "DnTwkxa6xtFB72w2t9PPrwuxksAR1Gb663UWTGLbVpYM", "isSigner": false, 
   "isWritable": true}, {"publicKey": 
   "9NUu2yxzfarkDRsC82hhqdU6Bg6DnHiysteLvbQtkSMq", "isSigner": false, 
   "isWritable": true}, {"publicKey": 
   "27YLmwU5vJSFyNFfGZLhcfe3j6YZ8sEAgcbgFVviVfsW", "isSigner": true, "isWritable": 
   true}], programId: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA, data: [3, 3, 
   0, 0, 0, 0, 0, 0, 0])], recentBlockhash: 
   Optional("EbZuX2LgdpRcxbKxrA3R9vNgbGXcrBTPXo9fnqsHg9ay")), signers: 
   [SolanaSwift.Account(phrase: ["when", "weather", "wrist", "feed", "report", "claim", 
   "patient", "palace", "tail", "bridge", "rail", "hint"], publicKey: 
   27YLmwU5vJSFyNFfGZLhcfe3j6YZ8sEAgcbgFVviVfsW, secretKey: 64 bytes)], 
   expectedFee: SolanaSwift.FeeAmount(transaction: 5000, accountBalances: 2039280, 
   deposit: 0, others: nil)), realDestination: 
   "W3LJP23kwe4Vt6E2cpZ5DRHSNiJxfYwTxg8zuTmTKAT")

Іs there a way to get error description from "blockchainClient.sendTransaction" method?

**Comment by bigearsenal** [comment]
You can't do that. The decimals for usdc is 6. Plus, the mint address for usdc seems not correct.

**Comment by bigearsenal** [comment]
Obviously the token you are sending is SolChicks and its decimals is 9.
https://explorer.solana.com/address/cxxShYRVcepDudXhe7U62QHvw8uBJoKFifmzggGKVC2
pleas make sure that you understand token mint, decimal aspect before doing anything on Solana network

**Comment by bigearsenal** [comment]
The error you print is just the a string, not error itself.
```swift
catch {
            print("error")
        }
        ```

**Comment by bigearsenal** [comment]
Please make sure that you account has enough 0.002044280 SOL (5000+2039280 lamports) for paying fee also

**Comment by IhorStasiv** [comment]
Ok, now i can print my error end its say 

responseError(SolanaSwift.ResponseError(code: Optional(-32002), message: Optional("Transaction simulation failed: Attempt to debit an account but found no record of a prior credit."), data: Optional(SolanaSwift.ResponseErrorData(logs: Optional([]), numSlotsBehind: nil))))
